### ISSUE TITLE
Support for Alternate Travel Speeds

### ISSUE THREAD

**Issue by deraviin** [rinnocenti/travel-pace#2]
Feature Request: This is a lovely system, wondering if it would be possible to make the values for travel variable for modules/terrains that specify different travel times, such as the Icewind Dale: Rime of the Frostmaiden, where you go 1/2 mile per hour on foot with snowshoes on snowy trails, and 1/4 mile per hour on difficult terrain mountains with snowshoes, rather than 3 miles.

**Comment by rinnocenti** [comment]
I believe it is easy to add a global configuration with the travel ratio.
