### ISSUE TITLE
Calculation Broken

### ISSUE THREAD

**Issue by deraviin** [rinnocenti/travel-pace#3]
I hate to say, it appears to not work now. I am sorry. The only calculation which is done correctly is for .5 miles. After that it goes a bit crazy. These screenshots were done in a test server with no other modules active to be sure.

When first opened:
 <a href="https://gyazo.com/d1f243d98b8d36b5c04290432eab2c9f"><img src="https://i.gyazo.com/d1f243d98b8d36b5c04290432eab2c9f.png" alt="Image from Gyazo" width="395.2"/></a>
 
 After any changes are made: (here I simply removed the 3 miles of difficult terrain)
 <a href="https://gyazo.com/bb9c609b8b8a0d3cb4e7fd2bd9eb5caa"><img src="https://i.gyazo.com/bb9c609b8b8a0d3cb4e7fd2bd9eb5caa.png" alt="Image from Gyazo" width="397.6"/></a>

**Comment by rinnocenti** [comment]
Fix in v 0.3.1
